### PR TITLE
fix rhs resizing of the last fixed column in the Grid

### LINKED ISSUE #1249: Issue resizing fixed column from the rhs
image

### PR DESCRIPTION
**Pull request by nebojsa-peric**
Fix #1249

### CODE REVIEW

File: packages/cx/src/widgets/grid/Grid.js [hunk 1]
```diff
@@ -532,15 +532,16 @@ export class Grid extends Container {
                if (e.buttons != 1) return;
                let resizeOverlayEl = document.createElement("div");
 
-               let headerTBody = e.target.parentElement.parentElement.parentElement;
+               let gridEl =
+                  e.target.parentElement.parentElement.parentElement.parentElement.parentElement.parentElement;
```
Comment (LazoJankovic) [inline packages/cx/src/widgets/grid/Grid.js:536]: 😵‍💫
